notifications:
  email: false

git:
  depth: 1

language: c

matrix:
  include:
    - name: "macOS 10.15.5"
      os: osx
      osx_image: xcode12
    - name: "Ubuntu 16.04"
      os: linux
      dist: xenial

script:
  - ./scripts/test.sh -v v1.1
