notifications:
  email: false

git:
  depth: 1

language: c

matrix:
  include:
    - name: "macOS"
      os: osx
      osx_image: xcode10.1
      # Beacause of https://stackoverflow.com/questions/50024731/ld-unrecognized-option-push-state-no-as-needed
      # we don't enable sanitizers on gcc
      env: ENABLE_SANITIZERS="-DENABLE_SANITIZERS=1"
    - name: "Ubuntu 16.04"
      os: linux
      dist: xenial

script:
  - sudo apt-get install gdb
  - mkdir -p build && cd build && cmake ..
  - cmake --build . --config Debug
  - ./ruc ../tests/executable/floatsign.c
#  - gdb -ex run --args ./ruc ../tests/executable/floatsign.c
