notifications:
  email: false

git:
  depth: 1

language: c

matrix:
  include:
    - name: "macOS"
      os: osx
      osx_image: xcode10.1
      # Beacause of https://stackoverflow.com/questions/50024731/ld-unrecognized-option-push-state-no-as-needed
      # we don't enable sanitizers on gcc
      env: ENABLE_SANITIZERS="-DENABLE_SANITIZERS=1"
    - name: "Ubuntu 16.04"
      os: linux
      dist: xenial

script:
  - ./scripts/test.sh -v v1.1 -d
#  - sudo apt-get -y install gdb
#  - mkdir build && cd build && cmake .. && cd ..
#  - cmake --build build --config Debug
#  - gdb -ex run --args ./build/ruc ./tests/errors/102.2/Masin/toint.c
#  - cat tmp
