notifications:
  email: false

git:
  depth: 1

language: c

matrix:
  include:
    - name: "macOS"
      os: osx
      osx_image: xcode10.1
      # Beacause of https://stackoverflow.com/questions/50024731/ld-unrecognized-option-push-state-no-as-needed
      # we don't enable sanitizers on gcc
      env: ENABLE_SANITIZERS="-DENABLE_SANITIZERS=1"
      install:
        - brew install gdb
    - name: "Ubuntu 16.04"
      os: linux
      dist: xenial
      install:
        - apt-get install gdb

script:
#  - ./scripts/test.sh -v v1.1 -d
  - ./scripts/debug.sh ./tests/errors/RegressTests/sm=.c
