notifications:
  email: false

git:
  depth: 1

language: c

matrix:
  include:
    - name: "macOS"
      os: osx
      osx_image: xcode10.1
      # Beacause of https://stackoverflow.com/questions/50024731/ld-unrecognized-option-push-state-no-as-needed
      # we don't enable sanitizers on gcc
      env: ENABLE_SANITIZERS="-DENABLE_SANITIZERS=1"
    - name: "Ubuntu 16.04"
      os: linux
      dist: xenial
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - travis-ci/sqlite3
          packages:
            - gcc-7
            - g++-7
            - sqlite3
      env:
        - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"

before_install:
    - eval "${MATRIX_EVAL}"

script:
<<<<<<< HEAD
  - sudo apt-get install gdb
=======
  - eval "${MATRIX_EVAL}"
  - export CC=gcc-7
  - export CXX=g++-7
  - gcc --version
  - g++ --version
  - cmake --version
#  - sudo apt-get install gdb
>>>>>>> 4f047ae1e4da9fb9ac03c4dc24e9e6299e3b535a
  - mkdir -p build && cd build && cmake ..
  - cmake --build . --config Debug
  - ./ruc ../tests/executable/floatsign.c
#  - gdb -ex run --args ./ruc ../tests/executable/floatsign.c
